- name: Copy configuration
  become: true
  copy: src=configuration/ dest=/var/lib/jenkins/ owner=jenkins group=jenkins
- name: Create .m2 folder
  become: true
  file: path="/var/lib/jenkins/.m2" state=directory owner=jenkins group=jenkins
- name: Copy settings.xml
  become: true
  template:
    owner: jenkins
    group: jenkins
    src: settings.xml.j2
    dest: /var/lib/jenkins/.m2/settings.xml
- name: Set Jenkins URL
  become: yes
  template: 
    owner: jenkins
    group: jenkins
    src: jenkins.model.JenkinsLocationConfiguration.xml.j2
    dest: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml.yml
 
  # CSP needs to be disabled in order to make jbehave Reports look nice
- name: Disable Content Security Policy
  become: true
  lineinfile:
    path: /etc/default/jenkins
    line: 'JAVA_ARGS="${JAVA_ARGS} -Dhudson.model.DirectoryBrowserSupport.CSP=\"\" "'
- name: configure jenkins jobs
  include_tasks: job.yml
  vars: 
    job_name: "{{ item }}"
  with_items:
    - worblehat-pipelines
    - liquibase-dropAll-prod
    - liquibase-dropAll-test
- name: restart jenkins
  become: true
  service: name=jenkins state=restarted
- name: Add jenkins user to docker group
  become: true
  user:
    name: jenkins
    groups: docker
    append: yes