- name: Copy configuration
  become: true
  copy: src=configuration/ dest=/var/lib/jenkins/ owner=jenkins group=jenkins
- name: Create .m2 folder
  become: true
  file: path="/var/lib/jenkins/.m2" state=directory owner=jenkins group=jenkins
- name: Copy settings.xml
  become: true
  copy: src=configuration/settings.xml dest="/var/lib/jenkins/.m2" owner=jenkins group=jenkins
- include: job.yml
  job_name: worblehat-pipelines
  notify: restart jenkins
