---
- name: Create system user for sonar
  user:
    name: sonar
    comment: user to run SonarQube

- name: Download Sonar.
  get_url:
    url: "{{ sonar_download_url }}"
    dest: "{{ workspace }}/{{ sonar_version_directory }}.zip"

- name: Unzip Sonar.
  unarchive:
    src: "{{ workspace }}/{{ sonar_version_directory }}.zip"
    dest: /usr/local/
    copy: no
    creates: /usr/local/sonar/COPYING
    owner: sonar

- name: Move Sonar into place.
  shell: >
    mv /usr/local/{{ sonar_version_directory }} /usr/local/sonar
    creates=/usr/local/sonar/COPYING

- include_tasks: configure.yml
- include_tasks: plugins.yml

- name: Add sonar symlinks for service management.
  file:
    src: /usr/local/sonar/bin/linux-x86-64/sonar.sh
    dest: "{{ item }}"
    state: link
  with_items:
    - /usr/bin/sonar

- name: Copy sonar init script
  copy: src=system/ dest=/etc/systemd/system
  become: true

- name: create service for sonar
  raw: systemctl enable sonar
  become: true

- name: Ensure Sonar is running and set to start on boot.
  become: true
  systemd: name=sonar state=started enabled=yes

- include_tasks: change_admin_pw.yml

- include_tasks: update_jenkins.yml
