- name: Configure sonar webcontext
  become: true
  lineinfile:
    dest: /usr/local/sonar/conf/sonar.properties
    regexp: "^#sonar.web.context"
    line: "sonar.web.context=/sonar"
- name: Copy sonar plugins
  become: true
  copy: src=plugins/ dest=/usr/local/sonar/extensions/downloads/
- name: Restart sonar
  service: name=sonar state=restarted
  become: true
