- name: User Token if Successfully Created
  ansible.builtin.set_fact:
    sonar_ci_token: "{{ ciresponsetoken.json.token }}"
  when: ciresponsetoken.status == 200

- name: Update Jenkins with Token
  become: true
  template: src="jenkins/credentials.xml.j2" dest="/var/lib/jenkins/credentials.xml" owner=jenkins group=jenkins mode=0644
  when: sonar_ci_token is defined

- name: Update Jenkins with Token
  become: true
  template: src="jenkins/hudson.plugins.sonar.SonarGlobalConfiguration.xml.j2" dest="/var/lib/jenkins/hudson.plugins.sonar.SonarGlobalConfiguration.xml" owner=jenkins group=jenkins mode=0644
  when: sonar_ci_token is defined

- name: Update Jenkins with Token
  become: true
  template: src="jenkins/org.quality.gates.jenkins.plugin.GlobalConfig.xml.j2" dest="/var/lib/jenkins/org.quality.gates.jenkins.plugin.GlobalConfig.xml" owner=jenkins group=jenkins mode=0644
  when: sonar_ci_token is defined

