jenkins:
  build: docker/jenkins
  links:
  - artifactory
  - sonar
  - sonarmysql
  - worblehatweb
  - worblehatdb
  - prodworblehatweb
  - prodworblehatdb
  environment:
  - JENKINS_URL=http://jenkins:8080
  - ARTIFACTORY_URL=http://artifactory:8080/artifactory
  - SITE_DEPLOY_PATH=/home/jenkins/site-deploy/
  - WORBLEHAT_DB_HOST=worblehatdb
  - WORBLEHAT_TOMCAT_URL=http://worblehatweb:8080
  - WORBLEHAT_PRODUCTION_DB_HOST=prodworblehatdb
  - WORBLEHAT_PRODUCTION_TOMCAT_URL=http://prodworblehatweb:8080
  - SONAR_URL=http://sonar:9000/sonar
  - SONAR_DB_HOST=sonarmysql
  # Insert the correct worblehat git url
  - PROJECT_URL=https://github.com/scrum-for-developers/worblehat
  # Insert the Public IP here for acceptance-tests via saucelabs
  - PSD_SERVER=127.0.0.1 
  volumes:
  - mounted_directories/jenkins_home:/var/jenkins_home:rw
  - mounted_directories/site_deploy:/home/jenkins/site-deploy:rw
artifactory:
  image: mattgruter/artifactory:3.4.2
sonarmysql:
  image: tpires/sonar-mysql
  expose:
  - 3306
sonar:
  build: docker/sonar
  links:
  - sonarmysql:db
worblehatdb:
  image: mysql:5.6.22
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_USER=worblehat
  - MYSQL_PASSWORD=worblehat
  - MYSQL_DATABASE=worblehat
worblehatweb:
  build: docker/tomcat
  links:
  - worblehatdb
prodworblehatdb:
  image: mysql:5.6.22
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_USER=worblehat
  - MYSQL_PASSWORD=worblehat
  - MYSQL_DATABASE=worblehat
prodworblehatweb:
  build: docker/worblehat-host
  links:
  - prodworblehatdb:worblehatdb
nginx:
  build: docker/nginx
  ports:
  - "80:80"
  links:
  - jenkins
  - artifactory
  - sonar
  - worblehatweb
  - prodworblehatweb
  environment:
  - PROJECT_URL=https://github.com/scrum-for-developers/worblehat
  volumes:
  - mounted_directories/site_deploy/site:/usr/share/nginx/html/worblehat-site
