# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 6144
    v.cpus = 2
  end

  config.vm.define "scrum-for-developers-infra-box"

  # Workaround for "stdin: is not a tty error" -- make Vagrants ssh shell a non-login one
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.synced_folder "../", "/scrum-for-developers-infra"

  # Instead of using the Ansible provisioning provider we install Ansible in the
  # Vagrant box and let Ansible run locally. This way, though not exactly
  # straightforward, it also works in Windows without hassle (and it's a bit
  # faster, too).
  config.vm.provision :shell do |shell|
    shell.keep_color = true
    shell.inline = """
    cd /vagrant && \
    ./prepare-ansible.sh && \
    cd /scrum-for-developers-infra/ansible && \
    export PYTHONUNBUFFERED=1 && \
    ./provision-local.sh
    """
  end

  config.vm.network "forwarded_port", guest: 8000, host: 8000

end
