
- name: add ssh key when git url is using ssh and not https
  block:
    - name: create ~/.ssh/
      file: path="~/.ssh" state=directory owner=jenkins group=jenkins mode=0700

    - name: add git host to known hosts
      shell: ssh-keyscan -H {{ git_host }} >> ~/.ssh/known_hosts

    - name: add private ssh key for cloning git repos
      copy: 
        src: "{{ git_ssh_key_file }}"
        dest: ~/.ssh/id_rsa
        owner: jenkins
        group: jenkins
        mode: 0600
  when: git_url | truncate(7) == "git@..."
  become: true
  become_user: jenkins

- name: Set Jenkins URL
  become: yes
  template: 
    owner: jenkins
    group: jenkins
    src: jenkins.model.JenkinsLocationConfiguration.xml.j2
    dest: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml

- name: configure jenkins jobs
  include_tasks: job.yml
  vars: 
    job_name: "{{ item }}"
  with_items:
    - worblehat-pipelines
    - liquibase-dropAll-prod
    - liquibase-dropAll-test

- name: restart jenkins
  become: true
  service: name=jenkins state=restarted