- name: Copy configuration
  become: true
  copy: src=configuration/ dest=/var/lib/jenkins/ owner=jenkins group=jenkins
- name: Copy settings.xml
  become: true
  template:
    owner: jenkins
    group: jenkins
    src: settings.xml.j2
    dest: /var/lib/jenkins/.m2/settings.xml
- name: Set Jenkins URL
  become: yes
  template: 
    owner: jenkins
    group: jenkins
    src: jenkins.model.JenkinsLocationConfiguration.xml.j2
    dest: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
- name: configure jenkins jobs
  include_tasks: job.yml
  vars: 
    job_name: "{{ item }}"
  with_items:
    - worblehat-pipelines
    - liquibase-dropAll-prod
    - liquibase-dropAll-test
- name: restart jenkins
  become: true
  service: name=jenkins state=restarted