---
security_group: "created-by-ansible"
ec2_key_name: "scrum-for-developers"
instances:
  - name: infra-test
    team_title: Test-Team
    git_url: https://github.com/scrum-for-developers/worblehat.git
    git_web_url: https://github.com/scrum-for-developers/worblehat
