#- name: Download Spring Boot Admin Server Servlet
#  shell: mvn dependency:get -Dartifact=de.codecentric:spring-boot-admin-sample-servlet:2.2.2
- name: Create spring-boot-admin directory
  become: true
  file: path="/opt/spring-boot-admin" state=directory owner=root group=root mode=0777
- name: Copy spring boot admin servlet example
  copy:
    src: spring-boot-admin/spring-boot-admin-sample-servlet.jar
    dest: /opt/spring-boot-admin/spring-boot-admin-sample-servlet.jar
    mode: 0777
- name: Copy spring boot admin service
  copy:
    src: spring-boot-admin/spring-boot-admin.service
    dest: /opt/spring-boot-admin/spring-boot-admin.service
    mode: 0777



- name: Copy spring-boot-admin application.conf
  template: src=spring-boot-admin/application.properties.j2 dest="/opt/spring-boot-admin/application.properties"
- name: Link Spring Boot Admin Server to /etc/init.d
  become: true
  file: src="/opt/spring-boot-admin/spring-boot-admin.service" dest="/etc/systemd/system/spring-boot-admin.service" mode=0777 state=link
- name: Start Spring Boot Admin
  become: true
  service: name=spring-boot-admin state=restarted

- include_tasks: worblehat.yml
  vars:
    worblehat_stage: "test"
    worblehat_port: "9100"

- name: Create a database for worblehat-test
  mysql_db:
    name: "worblehat_test"
    state: present
    login_user: root
    login_password: root

- include_tasks: worblehat.yml
  vars:
    worblehat_stage: "prod"
    worblehat_port: "9101"

- name: Create a database for worblehat-prod
  mysql_db:
    name: "worblehat_prod"
    state: present
    login_user: root
    login_password: root

- name: Create a database user for worblehat
  mysql_user:
    name: "worblehat"
    host: "localhost"
    priv: "*.*:ALL"
    password: "worblehat"
    login_user: root
    login_password: root
