- include_tasks: worblehat.yml
  vars: 
    worblehat_stage: "test"
    worblehat_port: "9100"

- name: Create a database for worblehat-test
  mysql_db:
    name: "worblehat_test"
    state: present
    login_user: root
    login_password: root

- include_tasks: worblehat.yml
  vars:
    worblehat_stage: "prod"
    worblehat_port: "9101"

- name: Create a database for worblehat-prod
  mysql_db:
    name: "worblehat_prod"
    state: present
    login_user: root
    login_password: root

- name: Create a database user for worblehat
  mysql_user:
    name: "worblehat"
    host: "localhost"
    priv: "*.*:ALL"
    password: "worblehat"
    login_user: root
    login_password: root
