- name: Create worblehat directory
  become: true
  file: path="/opt/worblehat-{{ worblehat_stage }}" state=directory owner=root group=root mode=0777
- name: Copy woblehat application.conf
  template: src=application.properties.j2 dest="/opt/worblehat-{{ worblehat_stage }}/application.properties"
- name: Copy worblehat dummy script
  copy: src=worblehat.script dest="/opt/worblehat-{{ worblehat_stage}}/worblehat.jar" mode=0777
- name: Link worblehat to /etc/init.d
  become: true
  file: src="/opt/worblehat-{{ worblehat_stage }}/worblehat.jar" dest="/etc/init.d/worblehat-{{ worblehat_stage }}" mode=0777 state=link
- name: "Allow jenkins to sudo worblehat"
  become: yes
  lineinfile:
    dest: "/etc/sudoers"
    line: "jenkins ALL = NOPASSWD: /etc/init.d/worblehat-{{ worblehat_stage }}"
    state: "present"
