---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: ec2_create
      ec2_ami_id: "ami-0f6ea57bdd24be250"
      instances:
        - name: worblehat
          team_title: worblehat
          git_url: https://github.com/scrum-for-developers/worblehat.git
          git_web_url: https://github.com/scrum-for-developers/worblehat
