---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: ec2_create
      ec2_key_name: "scrumfordevelopers"
      ec2_region: "eu-central-1"
      ec2_ami_id: "ami-09f3b2b5c319f1103"  #Ubuntu 16.04 (Note that the id depends on the region!)
      instances:
        - name: worblehat
          team_title: worblehat
          git_url: https://github.com/scrum-for-developers/worblehat.git
          git_web_url: https://github.com/scrum-for-developers/worblehat
