---

- hosts: tag_ScrumForDevelopers_ScrumForDevelopers
  gather_facts: no
  vars:
      nginx_port: 80
      git_web_url: "{{ hostvars[inventory_hostname].tags.SfdGitWebUrl }}"
      git_url: "{{ hostvars[inventory_hostname].tags.SfdGitUrl }}"
      git_host: "{{ hostvars[inventory_hostname].tags.SfdGitUrl | regex_search('[\\w\\-\\.]*\\.(de|com)') }}"
      index_title: "Hello {{ hostvars[inventory_hostname].tags.SfdTeamTitle }} !"
      docker_user: "ubuntu"
      this_ip: "{{ hostvars[inventory_hostname].tags.SfdElasticIp }}"
      ansible_python_interpreter: python3

  pre_tasks:
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]

    - name: upgrade system if necessary
      become: true
      apt:
        update_cache: yes
        upgrade: safe
      register: apt_updates
      vars: 
        ansible_python_interpreter: python3

    - name: reboot if kernal was updated
      become: true
      reboot: 
      when: apt_updates.stdout_lines|select('regex', '^Setting up linux-image-\d+\.\d+\.\d+-\d+-aws \(.*\) \.\.\.$') is any

  roles:
    - role: nginx
    - role: artifactory
    - role: jenkins
    - role: worblehat