---

- hosts: tag_ScrumForDevelopers_ScrumForDevelopers
  gather_facts: no
  vars:
      nginx_port: 80
      git_web_url: "{{ hostvars[inventory_hostname].tags.SfdGitWebUrl }}"
      git_url: "{{ hostvars[inventory_hostname].tags.SfdGitUrl }}"
      # The provided regular expression is used to match strings that represent domain names with the top-level domain (TLD) being either "de" or "com." 
      git_host: "{{ hostvars[inventory_hostname].tags.SfdGitUrl | regex_search('[\\w\\-\\.]*\\.(de|com)') }}"
      index_title: "Hello {{ hostvars[inventory_hostname].tags.SfdTeamTitle }} !"
      docker_user: "ubuntu"
      this_ip: "{{ hostvars[inventory_hostname].tags.SfdElasticIp }}"
      ansible_python_interpreter: python3

  pre_tasks:
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]

    - name: hotfix sonar
      become: true
      lineinfile:
        dest: /usr/local/sonar/conf/sonar.properties
        regexp: "^sonar.plugins.risk.consent"
        line: sonar.plugins.risk.consent=ACCEPTED
    - name: restart sonar
      become: true
      systemd: name=sonar state=restarted
    - name: Ensure the service is enabled and started
      become: true
      service:
        name: "{{ item.service }}"
        enabled: yes
        state: started
      with_items:
        - service: "worblehat-test"
        - service: "worblehat-prod"
        - service: "spring-boot-admin"

  roles:
    - role: nginx
    - role: artifactory
    - role: jenkins
    - role: worblehat