- name: Add Artifactory apt key
  become: true
  apt_key:
    url:  https://releases.jfrog.io/artifactory/api/gpg/key/public

- name: Add Artifactory Repository
  become: true
  apt_repository:
    repo: deb https://releases.jfrog.io/artifactory/artifactory-debs xenial main

- name: update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Artifactory
  become: true
  apt:
    name: jfrog-artifactory-oss

- name: Initialize artifactory
  # https://jfrog.com/help/r/jfrog-installation-setup-documentation/artifactory-bootstrap-yaml-file
  become: true
  template: 
    src: artifactory.config.import.yml.j2
    dest: /opt/jfrog/artifactory/var/etc/artifactory/artifactory.config.import.yml

- name: Create access config directory
  become: true
  file: 
    path: /opt/jfrog/artifactory/var/etc/access/
    owner: artifactory
    group: artifactory
    state: directory  

- name: Initialize access
  # https://jfrog.com/help/r/jfrog-installation-setup-documentation/artifactory-bootstrap-yaml-file
  become: true
  template: 
    src: access.config.import.yml.j2
    dest: /opt/jfrog/artifactory/var/etc/access/access.config.import.yml

- name: Set admin default user
  # https://jfrog.com/help/r/jfrog-platform-administration-documentation/recreate-the-default-admin-user
  copy: 
    src:   bootstrap.creds 
    dest:  /opt/jfrog/artifactory/var/etc/access
    group: artifactory
    owner: artifactory
    mode:  '0600'
  become:  true

# earlier, the port was set here via system.yaml, but it defaults to 8081 which is fine

- name: Start Artifactory service
  become: true
  service:
    name: artifactory
    state: started
