---
dependencies:
- role: geerlingguy.jenkins
  become: true
  jenkins_url_prefix: "/jenkins"
  jenkins_package_state: latest
  jenkins_plugins_install_dependencies: true
  jenkins_plugins_state: latest
  jenkins_plugins:
    - artifactory
    - build-monitor-plugin
    - embeddable-build-status
    - git
    - lockable-resources # for locking dev and prod env while deployments
    - htmlpublisher
    - blueocean
