---
dependencies:
- role: geerlingguy.jenkins
  become: true
  jenkins_url_prefix: "/jenkins"
  jenkins_version: "2.116"
  jenkins_plugins:
    - artifactory
    - batch-task
    - build-name-setter
    - build-pipeline-plugin
    - chucknorris
    - clone-workspace-scm
    - copyartifact
    - delivery-pipeline-plugin
    - deploy
    - embeddable-build-status
    - git-client
    - github-api
    - github
    - git
    - gitlab-hook
    - html-audio-notifier
    - jenkinswalldisplay
    - jquery
    - join
    - mercurial
    - promoted-builds
    - ruby-runtime
    - scm-api
    - token-macro
    - parameterized-trigger
    # Job DSL
    - job-dsl
    - script-security
    - structs
    # Git
    - workflow-scm-step
    - credentials
    - matrix-project
    - mailer
    - ssh-credentials
    - workflow-step-api
    - apache-httpcomponents-client-4-api
    - jsch
    - display-url-api
    - junit
    - workflow-api
    # Pipeline DSL
    - workflow-multibranch
    - workflow-cps
    - workflow-support
    - branch-api
    - cloudbees-folder
    - workflow-job
    - ace-editor
    - jquery-detached
