---
dependencies:
- role: geerlingguy.jenkins
  # https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/jenkins/documentation/
  become: true
  jenkins_url_prefix: "/jenkins"
  jenkins_http_port: 8080
  jenkins_admin_username: admin
  jenkins_admin_password: Hell0PSD!
  jenkins_package_state: latest
  jenkins_plugins_install_dependencies: true
  jenkins_plugins_state: latest
  jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Dhudson.model.DirectoryBrowserSupport.CSP=\"\""
  jenkins_plugins:
    - artifactory
    - build-monitor-plugin
    - embeddable-build-status
    - git
    - htmlpublisher
    - blueocean
    - workflow-aggregator # Pipelines
    - cucumber-reports
    - sonar
    - sonar-quality-gates
    - lockable-resources
    - pipeline-stage-view