---
dependencies:
- role: geerlingguy.jenkins
  become: true
  jenkins_url_prefix: "/jenkins"
  jenkins_version: "2.116"
  jenkins_plugins:
    - artifactory
    - batch-task
    - build-name-setter
    - build-pipeline-plugin
    - chucknorris
    - clone-workspace-scm
    - copyartifact
    - delivery-pipeline-plugin
    - deploy
    - embeddable-build-status
    - git-client
    - github-api
    - github
    - git
    - gitlab-hook
    - html-audio-notifier
    - jenkinswalldisplay
    - jquery
    - join
    - promoted-builds
    - ruby-runtime
    - scm-api
    - token-macro
    - parameterized-trigger
    # Job DSL
    - job-dsl
    - script-security
    - structs
    # Git
    - workflow-scm-step
    - credentials
    - matrix-project
    - mailer
    - ssh-credentials
    - workflow-step-api
    - apache-httpcomponents-client-4-api
    - jsch
    - display-url-api
    - junit
    - workflow-api
    # Pipeline DSL
    - ace-editor
    - branch-api
    - cloudbees-folder
    - jquery-detached
    - workflow-cps
    - workflow-job
    - workflow-multibranch
    - workflow-support
    # Blue Ocean
    - jenkins-design-language
    - blueocean-core-js
    - github-branch-source
    - blueocean-commons
    - blueocean-rest
    - pubsub-light
    - blueocean-pipeline-scm-api
    - htmlpublisher
    - variant
    - blueocean-web
    - blueocean-jwt
    - favorite
    - blueocean-rest-impl
    - blueocean-pipeline-api-impl
    - blueocean-github-pipeline
    - blueocean-git-pipeline
    - blueocean-config
    - mercurial
    - handy-uri-templates-2-api
    - cloudbees-bitbucket-branch-source
    - blueocean-bitbucket-pipeline
    - blueocean-dashboard
    - blueocean-personalization
    - jira
    - blueocean-jira
    - blueocean-display-url
    - sse-gateway
    - blueocean-events
    - blueocean-pipeline-editor
    - blueocean-i18n
    - blueocean-autofavorite
    - blueocean
