- name: Clone scrum-developers-infra-repo
  git: repo=https://github.com/scrum-for-developers/scrum-for-developers-infra dest={{ infra_dir }} update=yes force=yes
- name: Install docker-compose
  become: true
  pip: name=docker-compose
- name: Make docker-compose executable
  become: true
  file: path=/usr/local/bin/docker-compose mode=755
- name: Add provisioning user to docker group
  become: true
  user: name="{{ docker_user }}" groups=docker append=yes
- name: Disable hostkey checking for ssh
  # to make deployment via ssh to docker container possible
  become: true
  lineinfile:
    dest: /etc/ssh/ssh_config
    regexp: "^#( *)StrictHostKeyChecking"
    line: "StrictHostKeyChecking=no"
- name: Start docker-compose with nohup
  shell: "nohup docker-compose up > docker-compose.log 2> docker-compose.error.log &"
  args:
    chdir: "{{ infra_dir }}/docker"
