# Playbook for docker installation
---

- hosts: all
  vars:
    config_dir: "{{ ansible_env.HOME }}/dev_env"
  tasks:
  - name: Install Docker
    sudo: True
    yum: name=docker state=latest
  - name: Install Git
    sudo: True
    yum: name=git state=latest
  - name: Add provisioning user to docker group
    sudo: True
    user: name=ec2-user groups=docker append=yes
  - name: Clone scrum-developers-infra-repo
    git: repo=https://github.com/scrum-for-developers/scrum-for-developers-infra dest={{ config_dir }} update=yes force=yes
  - name: Create site-deploy directory
    file: path={{ config_dir }}/site-deploy/site state=directory mode=777
  - name: Start docker service
    sudo: True
    service: name=docker state=started
  - name: Install docker-compose
    sudo: True
    pip: name=docker-compose
  - name: Make docker-compose executable
    sudo: True
    file: path=/usr/local/bin/docker-compose mode=755
