# Playbook for docker installation
---

- hosts: all
  vars:
    config_dir: "{{ ansible_env.HOME }}/dev_env"
  tasks:
  - name: Install Docker
    sudo: True
    yum: name=docker state=latest
  - name: Install Git
    sudo: True
    yum: name=git state=latest
  - name: Install fig
    sudo: True
    action: shell curl -L https://github.com/docker/fig/releases/download/1.0.1/fig-`uname -s`-`uname -m` > /usr/local/bin/fig; chmod +x /usr/local/bin/fig
  - name: Add provisioning user to docker group
    sudo: True
    action: shell usermod -a -G docker `whoami`
  - name: Clone scrum-developers-infra-repo
    git: repo=https://github.com/scrum-for-developers/scrum-for-developers-infra dest={{ config_dir }} update=yes force=yes
  - name: Create site-deploy directory
    file: path={{ config_dir }}/site-deploy/site state=directory mode=777
  - name: Start docker service
    service: name=docker state=started
