---

- hosts: tag_ScrumForDevelopers_ScrumForDevelopers
  gather_facts: no
  vars:
      nginx_port: 80
      git_web_url: "{{ ec2_tag_SfdGitWebUrl }}"
      git_url: "{{ ec2_tag_SfdGitUrl }}"
      index_title: "Hello {{ ec2_tag_SfdTeamTitle }} !"
      this_ip: "{{ ec2_tag_SfdElasticIp }}"
  pre_tasks:
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]
    - name: update repositories
      raw: sudo apt-get update
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
    - name: Gathering facts
      setup:
  roles:
    - role: util
    - role: java8
    - role: geerlingguy.mysql
      become: true
    - role: nginx
    - role: jenkins
    - role: maven
      maven_mirror: http://archive.apache.org/dist/maven/binaries/
    - role: sonar
      become: true
    - role: worblehat
