---

- hosts: local
  connection: local
  roles:
    - role: util
    - role: java8
    - role: nginx
      nginx_port: 8000
    - role: jenkins
    - role: docker
      docker_user: "vagrant"
    - role: maven
    - role: sonar
