---
- hosts: tag_ScrumForDevelopersImage_ScrumForDevelopersImage
  gather_facts: no
  vars:
    nginx_port: 80
    git_web_url: "{{ hostvars[inventory_hostname].tags.SfdGitWebUrl }}"
    git_url: "{{ hostvars[inventory_hostname].tags.SfdGitUrl }}"
    index_title: "Hello {{ hostvars[inventory_hostname].tags.SfdTeamTitle }} !"
    this_ip: "{{ hostvars[inventory_hostname].tags.SfdElasticIp }}"

  pre_tasks:
    - name: Gathering facts
      setup:

    - name: Set ansible_python_interpreter - required by some geerlingguy roles - to default python executable
      set_fact: ansible_python_interpreter={{ hostvars[inventory_hostname].ansible_python.executable }}

    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]

    - name: upgrade system if necessary
      become: true
      apt:
        update_cache: yes
        upgrade: safe
      register: apt_updates

    - name: reboot if kernal was updated
      become: true
      reboot: 
      when: apt_updates.stdout_lines|select('regex', '^Setting up linux-image-\d+\.\d+\.\d+-\d+-aws \(.*\) \.\.\.$') is any

  roles:
    - role: util
    - role: geerlingguy.java
      become: true
      java_packages: 
        - openjdk-17-jdk-headless
    - role: geerlingguy.docker
      become: true
    - role: geerlingguy.mysql
      # for artifactory & worblehat
      become: true
    - role: geerlingguy.postgresql
      # for sonar
      become: true
      postgresql_databases:
        - name: "{{ sonar_db }}"
      postgresql_users:
        - name: "{{ sonar_db_username }}"
          password: "{{ sonar_db_password }}"
    - role: nginx
    - role: artifactory
    - role: maven
    - role: jenkins
    - role: sonar
      become: true
#    - role: worblehat
