---

- hosts: tag_ScrumForDevelopers_ScrumForDevelopers
  vars:
      nginx_port: 80
      git_web_url: "{{ ec2_tag_SfdGitWebUrl }}"
      git_url: "{{ ec2_tag_SfdGitUrl }}"
      index_title: "Hello {{ ec2_tag_SfdTeamTitle }} !"
      docker_user: "ubuntu"
      this_ip: "{{ ec2_tag_SfdElasticIp }}"
  pre_tasks:
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]
  roles:
    - role: util
    - role: java8
    - role: geerlingguy.mysql
      become: true
    - role: nginx
    - role: jenkins
    - role: docker
    - role: maven
    - role: sonar
      become: true
    - role: worblehat
