---
- hosts: tag_ScrumForDevelopersImage_ScrumForDevelopersImage
  gather_facts: no
  vars:
    nginx_port: 80
    git_web_url: "{{ ec2_tag_SfdGitWebUrl }}"
    git_url: "{{ ec2_tag_SfdGitUrl }}"
    index_title: "Hello {{ ec2_tag_SfdTeamTitle }} !"
    this_ip: "{{ ec2_tag_SfdElasticIp }}"
    ansible_python_interpreter: python3

  pre_tasks:
    - name: Gathering facts
      setup:
      vars: 
        ansible_python_interpreter: python3
  
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]

    - name: upgrade system if necessary
      become: true
      apt:
        update_cache: yes
        upgrade: safe
      register: apt_updates
      vars: 
        ansible_python_interpreter: python3

    - name: install python-psycopg2
      become: true
      apt:
        pkg:
        - python-psycopg2
        - python-pymysql
        - python3-pymysql
        state: present
      vars: 
        ansible_python_interpreter: python3

    - name: reboot if kernal was updated
      become: true
      reboot: 
      when: apt_updates.stdout_lines|select('regex', '^Setting up linux-image-\d+\.\d+\.\d+-\d+-aws \(.*\) \.\.\.$') is any

  roles:
    - role: util
    - role: java11
      become: true
    - role: geerlingguy.docker
      become: true
    - role: geerlingguy.mysql
      become: true
    - role: geerlingguy.postgresql
      become: yes
    - role: nginx
    - role: artifactory
    - role: maven
      maven_mirror: http://archive.apache.org/dist/maven/binaries/
    - role: jenkins
    - role: sonar
      become: true
      vars: 
        ansible_python_interpreter: python2.7
    - role: worblehat
