---

- hosts: tag_ScrumForDevelopers_ScrumForDevelopers
  roles:
    - role: util
    - role: java8
    - role: nginx
      nginx_port: 80
      git_web_url: "{{ ec2_tag_SfdGitWebUrl }}"
      index_title: "Hello {{ ec2_tag_SfdTeamTitle }} !"
    - role: jenkins
    - role: docker
      docker_user: "ec2-user"
    - role: maven
    - role: sonar
