---

- hosts: local
  connection: local
  tasks:
    - name: Disable hostkey checking for ssh
      # to make deployment via ssh to docker container possible
      become: true
      lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: "^#( *)StrictHostKeyChecking"
        line: "StrictHostKeyChecking=no"
