- include_tasks: create_security_group.yml

- include_tasks: create_instance.yml
  vars:
    instance_name: "{{ item.name }}"
    team_title: "{{ item.team_title }}"
    git_url: "{{ item.git_url }}"
    git_web_url: "{{ item.git_web_url }}"
  with_items: "{{ instances }}"
