- name: Create EC2 instance
  ec2:
    instance_type: m5.xlarge
    key_name: "{{ ec2_key_name }}"
    region: "{{ ec2_region }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 24
        delete_on_termination: true
    exact_count: 1
    count_tag:
      Name: "sfd-{{ instance_name }}"
    instance_tags:
      Name: "sfd-{{ instance_name }}"
      ScrumForDevelopersImage: "ScrumForDevelopersImage"
      SfdTeamTitle: "{{ team_title }}"
      SfdGitUrl: "{{ git_url }}"
      SfdGitWebUrl: "{{ git_web_url }}"
    image: "{{ ec2_ami_id }}"
    group: "{{ ec2_security_group }}"
    wait: yes
  register: ec2

- name: Debug created instance
  debug: var=ec2

- name: Wait for SSH to come up
  delegate_to: "{{ instance.public_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  loop: "{{ ec2.instances }}"
  loop_control:
    loop_var: instance
#  when: ec2.changed

- name: Assign elastic ip
  ec2_eip:
    region: "{{ ec2_region }}"
    device_id: "{{ ec2.instance_ids[0] }}"
  register: eip
  when: ec2.changed

- name: Debug elastic ip
  debug: var=eip

- name: Save elastic ip as tag
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ ec2.instance_ids[0] }}"
    tags:
      SfdElasticIp: "{{ eip.public_ip }}"
  when: eip.changed
