- name: Create EC2 instances
  ec2:
    instance_type: m4.large
    key_name: "{{ ec2_key_name }}"
    region: eu-west-1
    exact_count: 1
    count_tag:
      Name: "sfd-{{ instance_name }}"
    instance_tags:
      Name: "sfd-{{ instance_name }}"
      ScrumForDevelopers: "ScrumForDevelopers"
      SfdTeamTitle: "{{ team_title }}"
      SfdGitUrl: "{{ git_url }}"
      SfdGitWebUrl: "{{ git_web_url }}"
    image: ami-47a23a30 #Ubuntu 14.04
    group: "{{ security_group }}"
    wait: yes
  register: ec2
- name: Debug created instances
  debug: var=ec2
- name: Assign elastic ips
  ec2_eip:
    region: eu-west-1
    device_id: "{{ ec2.instance_ids[0] }}"
  register: eip
- name: Debug elastic ip
  debug: var=eip
- name: Save elastic ip as tag
  ec2_tag:
    region: eu-west-1
    resource: "{{ ec2.instance_ids[0] }}"
    tags:
      SfdElasticIp: "{{ eip.public_ip }}"
