- name: Create EC2 instance
  ec2:
    instance_type: m4.xlarge
    key_name: "{{ ec2_key_name }}"
    region: "{{ ec2_region }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 24
        delete_on_termination: true
    exact_count: 1
    count_tag:
      Name: "sfd-{{ instance_name }}"
    instance_tags:
      Name: "sfd-{{ instance_name }}"
      ScrumForDevelopers: "ScrumForDevelopers"
      SfdTeamTitle: "{{ team_title }}"
      SfdGitUrl: "{{ git_url }}"
      SfdGitWebUrl: "{{ git_web_url }}"
    image: "{{ ec2_ami_id }}"
    group: "{{ ec2_security_group }}"
    wait: yes
  register: ec2
- name: Debug created instance
  debug: var=ec2
- name: Assign elastic ip
  ec2_eip:
    region: "{{ ec2_region }}"
    device_id: "{{ ec2.instance_ids[0] }}"
  register: eip
- name: Debug elastic ip
  debug: var=eip
- name: Save elastic ip as tag
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ ec2.instance_ids[0] }}"
    tags:
      SfdElasticIp: "{{ eip.public_ip }}"
