- name: Create AWS security group
  ec2_group:
    name: "{{ security_group }}"
    description: "{{ security_group }}"
    region: "eu-west-1"
    rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
    rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
- include: create_instance.yml
  vars:
    instance_name: "{{ item.name }}"
    team_title: "{{ item.team_title }}"
    git_url: "{{ item.git_url }}"
    git_web_url: "{{ item.git_web_url }}"
  with_items: "{{ instances }}"
